name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master

env:
  IMAGE: unifieddevtools # image name
  IMAGE_TAG: latest # image tag

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    environment: sit

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Login to Docker Hub
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "${{ secrets.DOCKER_USERNAME }}/$IMAGE:$IMAGE_TAG" \
          .

    # Push the Docker image to Docker Hub
    - name: Publish
      run: |-
        docker push "${{ secrets.DOCKER_USERNAME }}/$IMAGE:$IMAGE_TAG"
